// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shared/proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_shared_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CountryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Clicks        uint64                 `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryStats) Reset() {
	*x = CountryStats{}
	mi := &file_shared_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryStats) ProtoMessage() {}

func (x *CountryStats) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryStats.ProtoReflect.Descriptor instead.
func (*CountryStats) Descriptor() ([]byte, []int) {
	return file_shared_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *CountryStats) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CountryStats) GetClicks() uint64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	TotalClicks   uint64                 `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	LastClickedAt string                 `protobuf:"bytes,3,opt,name=last_clicked_at,json=lastClickedAt,proto3" json:"last_clicked_at,omitempty"`
	TopCountries  []*CountryStats        `protobuf:"bytes,4,rep,name=top_countries,json=topCountries,proto3" json:"top_countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_shared_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatsResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetStatsResponse) GetTotalClicks() uint64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *GetStatsResponse) GetLastClickedAt() string {
	if x != nil {
		return x.LastClickedAt
	}
	return ""
}

func (x *GetStatsResponse) GetTopCountries() []*CountryStats {
	if x != nil {
		return x.TopCountries
	}
	return nil
}

var File_shared_proto_stats_proto protoreflect.FileDescriptor

const file_shared_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x18shared/proto/stats.proto\x12\x05stats\"%\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"@\n" +
	"\fCountryStats\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x04R\x06clicks\"\xab\x01\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x04R\vtotalClicks\x12&\n" +
	"\x0flast_clicked_at\x18\x03 \x01(\tR\rlastClickedAt\x128\n" +
	"\rtop_countries\x18\x04 \x03(\v2\x13.stats.CountryStatsR\ftopCountries2K\n" +
	"\fStatsService\x12;\n" +
	"\bGetStats\x12\x16.stats.GetStatsRequest\x1a\x17.stats.GetStatsResponseB=Z;github.com/StanislavYaroslavtsev/url-shortener/shared/protob\x06proto3"

var (
	file_shared_proto_stats_proto_rawDescOnce sync.Once
	file_shared_proto_stats_proto_rawDescData []byte
)

func file_shared_proto_stats_proto_rawDescGZIP() []byte {
	file_shared_proto_stats_proto_rawDescOnce.Do(func() {
		file_shared_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_stats_proto_rawDesc), len(file_shared_proto_stats_proto_rawDesc)))
	})
	return file_shared_proto_stats_proto_rawDescData
}

var file_shared_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_proto_stats_proto_goTypes = []any{
	(*GetStatsRequest)(nil),  // 0: stats.GetStatsRequest
	(*CountryStats)(nil),     // 1: stats.CountryStats
	(*GetStatsResponse)(nil), // 2: stats.GetStatsResponse
}
var file_shared_proto_stats_proto_depIdxs = []int32{
	1, // 0: stats.GetStatsResponse.top_countries:type_name -> stats.CountryStats
	0, // 1: stats.StatsService.GetStats:input_type -> stats.GetStatsRequest
	2, // 2: stats.StatsService.GetStats:output_type -> stats.GetStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_stats_proto_init() }
func file_shared_proto_stats_proto_init() {
	if File_shared_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_stats_proto_rawDesc), len(file_shared_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_stats_proto_goTypes,
		DependencyIndexes: file_shared_proto_stats_proto_depIdxs,
		MessageInfos:      file_shared_proto_stats_proto_msgTypes,
	}.Build()
	File_shared_proto_stats_proto = out.File
	file_shared_proto_stats_proto_goTypes = nil
	file_shared_proto_stats_proto_depIdxs = nil
}
