// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/StanislavYaroslavtsev/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkServiceInterface creates a new instance of MockLinkServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkServiceInterface {
	mock := &MockLinkServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkServiceInterface is an autogenerated mock type for the LinkServiceInterface type
type MockLinkServiceInterface struct {
	mock.Mock
}

type MockLinkServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkServiceInterface) EXPECT() *MockLinkServiceInterface_Expecter {
	return &MockLinkServiceInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockLinkServiceInterface
func (_mock *MockLinkServiceInterface) Create(ctx context.Context, url string, expiresAt *time.Time) (*domain.Link, error) {
	ret := _mock.Called(ctx, url, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *time.Time) (*domain.Link, error)); ok {
		return returnFunc(ctx, url, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *time.Time) *domain.Link); ok {
		r0 = returnFunc(ctx, url, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *time.Time) error); ok {
		r1 = returnFunc(ctx, url, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLinkServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - expiresAt *time.Time
func (_e *MockLinkServiceInterface_Expecter) Create(ctx interface{}, url interface{}, expiresAt interface{}) *MockLinkServiceInterface_Create_Call {
	return &MockLinkServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, url, expiresAt)}
}

func (_c *MockLinkServiceInterface_Create_Call) Run(run func(ctx context.Context, url string, expiresAt *time.Time)) *MockLinkServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLinkServiceInterface_Create_Call) Return(link *domain.Link, err error) *MockLinkServiceInterface_Create_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkServiceInterface_Create_Call) RunAndReturn(run func(ctx context.Context, url string, expiresAt *time.Time) (*domain.Link, error)) *MockLinkServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockLinkServiceInterface
func (_mock *MockLinkServiceInterface) Get(ctx context.Context, code string) (*domain.Link, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkServiceInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLinkServiceInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockLinkServiceInterface_Expecter) Get(ctx interface{}, code interface{}) *MockLinkServiceInterface_Get_Call {
	return &MockLinkServiceInterface_Get_Call{Call: _e.mock.On("Get", ctx, code)}
}

func (_c *MockLinkServiceInterface_Get_Call) Run(run func(ctx context.Context, code string)) *MockLinkServiceInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkServiceInterface_Get_Call) Return(link *domain.Link, err error) *MockLinkServiceInterface_Get_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkServiceInterface_Get_Call) RunAndReturn(run func(ctx context.Context, code string) (*domain.Link, error)) *MockLinkServiceInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockLinkServiceInterface
func (_mock *MockLinkServiceInterface) Ping(ctx context.Context) map[string]error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 map[string]error
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]error); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}
	return r0
}

// MockLinkServiceInterface_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockLinkServiceInterface_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLinkServiceInterface_Expecter) Ping(ctx interface{}) *MockLinkServiceInterface_Ping_Call {
	return &MockLinkServiceInterface_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockLinkServiceInterface_Ping_Call) Run(run func(ctx context.Context)) *MockLinkServiceInterface_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkServiceInterface_Ping_Call) Return(stringToErr map[string]error) *MockLinkServiceInterface_Ping_Call {
	_c.Call.Return(stringToErr)
	return _c
}

func (_c *MockLinkServiceInterface_Ping_Call) RunAndReturn(run func(ctx context.Context) map[string]error) *MockLinkServiceInterface_Ping_Call {
	_c.Call.Return(run)
	return _c
}
