// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StanislavYaroslavtsev/url-shortener/services/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkRepository creates a new instance of MockLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkRepository {
	mock := &MockLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkRepository is an autogenerated mock type for the LinkRepository type
type MockLinkRepository struct {
	mock.Mock
}

type MockLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkRepository) EXPECT() *MockLinkRepository_Expecter {
	return &MockLinkRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLinkRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLinkRepository_Expecter) Close() *MockLinkRepository_Close_Call {
	return &MockLinkRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLinkRepository_Close_Call) Run(run func()) *MockLinkRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLinkRepository_Close_Call) Return(err error) *MockLinkRepository_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Close_Call) RunAndReturn(run func() error) *MockLinkRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Delete(ctx context.Context, code string) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLinkRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockLinkRepository_Expecter) Delete(ctx interface{}, code interface{}) *MockLinkRepository_Delete_Call {
	return &MockLinkRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, code)}
}

func (_c *MockLinkRepository_Delete_Call) Run(run func(ctx context.Context, code string)) *MockLinkRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Delete_Call) Return(err error) *MockLinkRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, code string) error) *MockLinkRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Get(ctx context.Context, code string) (*domain.Link, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLinkRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockLinkRepository_Expecter) Get(ctx interface{}, code interface{}) *MockLinkRepository_Get_Call {
	return &MockLinkRepository_Get_Call{Call: _e.mock.On("Get", ctx, code)}
}

func (_c *MockLinkRepository_Get_Call) Run(run func(ctx context.Context, code string)) *MockLinkRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Get_Call) Return(link *domain.Link, err error) *MockLinkRepository_Get_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkRepository_Get_Call) RunAndReturn(run func(ctx context.Context, code string) (*domain.Link, error)) *MockLinkRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockLinkRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLinkRepository_Expecter) Ping(ctx interface{}) *MockLinkRepository_Ping_Call {
	return &MockLinkRepository_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockLinkRepository_Ping_Call) Run(run func(ctx context.Context)) *MockLinkRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Ping_Call) Return(err error) *MockLinkRepository_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockLinkRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Save(ctx context.Context, link *domain.Link) error {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Link) error); ok {
		r0 = returnFunc(ctx, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLinkRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
func (_e *MockLinkRepository_Expecter) Save(ctx interface{}, link interface{}) *MockLinkRepository_Save_Call {
	return &MockLinkRepository_Save_Call{Call: _e.mock.On("Save", ctx, link)}
}

func (_c *MockLinkRepository_Save_Call) Run(run func(ctx context.Context, link *domain.Link)) *MockLinkRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Link
		if args[1] != nil {
			arg1 = args[1].(*domain.Link)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Save_Call) Return(err error) *MockLinkRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Save_Call) RunAndReturn(run func(ctx context.Context, link *domain.Link) error) *MockLinkRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
