// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StanislavYaroslavtsev/url-shortener/services/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClickProducer creates a new instance of MockClickProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClickProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClickProducer {
	mock := &MockClickProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClickProducer is an autogenerated mock type for the ClickProducer type
type MockClickProducer struct {
	mock.Mock
}

type MockClickProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClickProducer) EXPECT() *MockClickProducer_Expecter {
	return &MockClickProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClickProducer
func (_mock *MockClickProducer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClickProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClickProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClickProducer_Expecter) Close() *MockClickProducer_Close_Call {
	return &MockClickProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClickProducer_Close_Call) Run(run func()) *MockClickProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClickProducer_Close_Call) Return(err error) *MockClickProducer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClickProducer_Close_Call) RunAndReturn(run func() error) *MockClickProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SendClickEvent provides a mock function for the type MockClickProducer
func (_mock *MockClickProducer) SendClickEvent(ctx context.Context, link *domain.Link, ip string) error {
	ret := _mock.Called(ctx, link, ip)

	if len(ret) == 0 {
		panic("no return value specified for SendClickEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Link, string) error); ok {
		r0 = returnFunc(ctx, link, ip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClickProducer_SendClickEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendClickEvent'
type MockClickProducer_SendClickEvent_Call struct {
	*mock.Call
}

// SendClickEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
//   - ip string
func (_e *MockClickProducer_Expecter) SendClickEvent(ctx interface{}, link interface{}, ip interface{}) *MockClickProducer_SendClickEvent_Call {
	return &MockClickProducer_SendClickEvent_Call{Call: _e.mock.On("SendClickEvent", ctx, link, ip)}
}

func (_c *MockClickProducer_SendClickEvent_Call) Run(run func(ctx context.Context, link *domain.Link, ip string)) *MockClickProducer_SendClickEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Link
		if args[1] != nil {
			arg1 = args[1].(*domain.Link)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClickProducer_SendClickEvent_Call) Return(err error) *MockClickProducer_SendClickEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClickProducer_SendClickEvent_Call) RunAndReturn(run func(ctx context.Context, link *domain.Link, ip string) error) *MockClickProducer_SendClickEvent_Call {
	_c.Call.Return(run)
	return _c
}
